<?php

require 'vendor/autoload.php';

/*
 * Aufgabe 1: Erzeuge eine neue Klasse im Namespace App\Entity.
 * Überlege dir jedoch zuerst, wie die Datenbank-Relation (Tabelle) aussehen wird.
 *
 * Importiere den Namespace TreptowKolleg\ORM\ORM
 *
 * benutze folgende Attribute für deine Properties:
 *
 * Primärschlüssel:                 #[ORM\Id]
 * Auto-Increment:                  #[ORM\AutoGenerated]
 * gemappt als Tabellen-Spalte:     #[ORM\Column]
 *
 * Beispiel:
 *
 * #[ORM\Id]
 * #[ORM\AutoGenerated]
 * #[ORM\Column(type: ORM\Types::Integer)]
 * private int $myId;
 *
 * #[ORM\Column(type: ORM\Types::String, length: 50, nullable: true)]
 * private string $nickName;
 */



/*
 * Aufgabe 2: Erzeuge anhand deiner neuen Klasse eine Datenbank-Relation (Tabelle).
 * Nutze hierfür den eigens entwickelten EntityManager!
 */


/*
 * Aufgabe 3: Erzeuge mehrere neue Objekte deiner erstellten Klasse und schreibe sie in die Datenbank.
 * Nutze auch hierfür den EntityManager!
 */

/*
 * Aufgabe 4: Rufe alle Datensätze aus der Relation ab und gib sie per print_r() aus.
 */


/*
 * Aufgabe 5: Rufe einen Datensatz anhand eines bestimmten Kriteriums ab.
 */

/*
 * Aufgabe 6: Verändere die Werte dieses Datensatzes und überschreibe ihn in der Datenbank.
 */