<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use TreptowKolleg\ORM\Attribute as DB;
use TreptowKolleg\ORM\Attribute\Type;
use TreptowKolleg\ORM\Exception\OrderByFormatException;
use TreptowKolleg\ORM\Exception\TypeNotSupportedException;

class Category
{
    #[DB\Id]
    #[DB\AutoGenerated]
    #[DB\Column(type: Type::Integer)]
    private ?int $id = null;

    #[DB\Column]
    private string $label;

    /**
     * @var null|Product[]
     */
    private ?array $products = null;

    private ProductRepository $repository;

    public function __construct(ProductRepository $repository = new ProductRepository())
    {
        $this->repository = $repository;
    }

    public function __toString(): string
    {
        return $this->getLabel();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): string
    {
        return $this->label;
    }

    public function setLabel(string $label): void
    {
        $this->label = $label;
    }

    /**
     * @return null|Product[]
     */
    public function getProducts(): ?array
    {
        try {
            if($this->products == null) {
               $this->products = $this->repository->findBy(["categoryId" => $this->getId()],['label' => 'ASC']);
            }
        } catch (OrderByFormatException|TypeNotSupportedException $e) {

        }
        return $this->products;
    }

}