<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use TreptowKolleg\ORM\ORM;
use TreptowKolleg\ORM\ORM\Types;

class Category
{
    #[ORM\Id]
    #[ORM\AutoGenerated]
    #[ORM\Column(type: Types::Integer)]
    private ?int $id = null;

    #[ORM\Column]
    private string $label;

    private CategoryRepository $repository;

    public function __construct()
    {
        $this->repository = new CategoryRepository();
    }

    public function __toString(): string
    {
        return $this->getLabel();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): string
    {
        return $this->label;
    }

    public function setLabel(string $label): void
    {
        $this->label = $label;
    }

    /**
     * @return Product[]
     */
    public function getProducts(): array
    {
        return $this->repository->findProducts($this->getId());
    }

}