<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use TreptowKolleg\ORM\Attribute as DB;
use TreptowKolleg\ORM\Attribute\Type;
use TreptowKolleg\ORM\Exception\OrderByFormatException;
use TreptowKolleg\ORM\Exception\TypeNotSupportedException;

class Category
{
    #[DB\Id]
    #[DB\AutoGenerated]
    #[DB\Column(type: Type::Integer)]
    private ?int $id = null;

    #[DB\Column]
    private string $label;

    private ProductRepository $repository;

    public function __construct()
    {
        $this->repository = new ProductRepository();
    }

    public function __toString(): string
    {
        return $this->getLabel();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): string
    {
        return $this->label;
    }

    public function setLabel(string $label): void
    {
        $this->label = $label;
    }

    /**
     * @return Product[]
     */
    public function getProducts(): array
    {
        try {
            return $this->repository->findBy(["categoryId" => $this->getId()],['label' => 'ASC']);
        } catch (OrderByFormatException|TypeNotSupportedException $e) {

        }
        return [];
    }

}