<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use TreptowKolleg\ORM\Attribute\Type;
use TreptowKolleg\ORM\Attribute as DB;

class Product
{
    #[DB\Id]
    #[DB\AutoGenerated]
    #[DB\Column(type: Type::Integer)]
    private ?int $id = null;

    #[DB\Column]
    private string $label;

    #[DB\Column(type: Type::Integer, nullable: true)]
    #[DB\ManyToOne(Category::class)]
    private ?int $categoryId = null;

    private ?Category $category = null;

    public function __construct()
    {
        if($this->categoryId) {
            $categoryRepo = new CategoryRepository();
            $this->category = $categoryRepo->find($this->categoryId);
        }
    }

    public function __toString(): string
    {
        return $this->getLabel();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): string
    {
        return $this->label;
    }

    public function setLabel(string $label): void
    {
        $this->label = $label;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): void
    {
        $this->categoryId = $category->getId();
        $this->category = $category;
    }

}