<?php

namespace App\Entity;

use TreptowKolleg\ORM\Attribute as DB;
use TreptowKolleg\ORM\Attribute\Type;

class SaveGame
{

    #[DB\Id]
    #[DB\AutoGenerated]
    #[DB\Column(type: Type::Integer)]
    private ?int $id = null;

    #[DB\Column(type: Type::Json)]
    private ?string $data = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getData(): ?object
    {
        return unserialize(json_decode($this->data));
    }

    public function setData(object $data): static
    {
        $this->data = json_encode(serialize($data));
        return $this;
    }

}