<?php

namespace App\Entity;

use TreptowKolleg\ORM\ORM;

class StoreLocation
{
    #[ORM\Id]
    #[ORM\AutoGenerated]
    #[ORM\Column(type: ORM\Types::Integer)]
    private ?int $id = null;

    #[ORM\Column(unique: true)]
    private string $label;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): string
    {
        return $this->label;
    }

    public function setLabel(string $label): void
    {
        $this->label = $label;
    }

}