<?php

namespace App\Entity;

use TreptowKolleg\ORM\Model\Repository;
use TreptowKolleg\ORM\ORM;
class Teacher
{

    #[ORM\Id]
    #[ORM\AutoGenerated]
    #[ORM\Column(type: ORM\Types::Integer)]
    private int $id;

    #[ORM\Column(length: 50)]
    private string $firstname;

    #[ORM\Column(length: 50)]
    private string $lastname;

    public function __toString(): string
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getFirstname(): string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): void
    {
        $this->firstname = $firstname;
    }

    public function getLastname(): string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): void
    {
        $this->lastname = $lastname;
    }

    /**
     * @return EmployeeList[]
     */
    public function getEmployeeList(): array
    {
        if(isset($this->id)) {
            return (new Repository(EmployeeList::class))->findBy(['teacher' => $this->id]);
        }
        return [];
    }

}