<?php

namespace App\Entity;

use TreptowKolleg\ORM\ORM;
class Teacher
{
    #[ORM\Id]               // Primary Key
    #[ORM\AutoGenerated]    // Auto Incremented
    #[ORM\Column]           // Map to Column
    private int $id;
    #[ORM\Column(length: 50)]
    private string $firstname;
    #[ORM\Column(length: 50)]
    private string $lastname;
    public function __toString(): string
    {
        return $this->firstname . ' ' . $this->lastname;
    }
    public function getId(): int
    {
        return $this->id;
    }
    public function getFirstname(): string
    {
        return $this->firstname;
    }
    public function getLastname(): string
    {
        return $this->lastname;
    }
}