<?php

namespace App\Entity;

use DateTime;
use TreptowKolleg\ORM\ORM\AutoGenerated;
use TreptowKolleg\ORM\ORM\Column;
use TreptowKolleg\ORM\ORM\CreatedAt;
use TreptowKolleg\ORM\ORM\Id;
use TreptowKolleg\ORM\ORM\Types;
use TreptowKolleg\ORM\ORM\UpdatedAt;

class User
{
    #[Id]
    #[AutoGenerated]
    #[Column(type: Types::Integer)]
    private ?int $id = null;

    #[Column(unique: true)]
    private string $username;

    #[Column]
    private string $firstname;

    #[Column]
    private string $lastname;

    #[CreatedAt]
    private ?string $created = null;
    #[UpdatedAt]
    private ?string $updated = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    public function getFirstname(): string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): void
    {
        $this->firstname = $firstname;
    }

    public function getLastname(): string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): void
    {
        $this->lastname = $lastname;
    }

    public function getCreated(): null|DateTime
    {
        if($this->updated) {
            return DateTime::createFromFormat("Y-m-d H:s:i", $this->created);
        }
        return null;
    }

    public function getUpdated(): null|DateTime
    {
        if($this->updated) {
            return DateTime::createFromFormat("Y-m-d H:s:i", $this->updated);
        }
        return null;
    }

}