<?php

namespace App\Entity;

use DateTime;
use TreptowKolleg\ORM\Attribute\Type;
use TreptowKolleg\ORM\Attribute as DB;

class User
{
    #[DB\Id]
    #[DB\AutoGenerated]
    #[DB\Column(type: Type::Integer)]
    private ?int $id = null;

    #[DB\Column(unique: true)]
    private string $username;

    #[DB\Column]
    private string $firstname;

    #[DB\Column]
    private string $lastname;

    #[DB\CreatedAt]
    private ?string $created = null;
    #[DB\UpdatedAt]
    private ?string $updated = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    public function getFirstname(): string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): void
    {
        $this->firstname = $firstname;
    }

    public function getLastname(): string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): void
    {
        $this->lastname = $lastname;
    }

    public function getCreated(): null|DateTime
    {
        if($this->updated) {
            return DateTime::createFromFormat("Y-m-d H:s:i", $this->created);
        }
        return null;
    }

    public function getUpdated(): null|DateTime
    {
        if($this->updated) {
            return DateTime::createFromFormat("Y-m-d H:s:i", $this->updated);
        }
        return null;
    }

}